before_install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - brew install node@10.15.2
install:
  - npm install
  - npm run ready
script:
  - npm run run